Newpanelhandler- updated PanelHandler code to new design
Spartronics4915/2019-DeepSpace pull request #57
Opened 2019-02-28 04:04 UTC by RyanOlney

2019-02-28 04:23 UTC, pietroglyph requested changes
See my comments.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/CargoIntake.java
> +            mMotorLeft = TalonSRXFactory.createDefaultTalon(Constants.kCargoIntakeMotorRight);
Just roll back your changes to this file.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +    private Solenoid mSolenoidArm = null;
Change `SolenoidArm` to `ArmSolenoid`... Change `Solenoid` to `ExtendSolenoid` or `SlideSolenoid`.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +            mSolenoidArm = new Solenoid(Constants.kCargoHatchArmPCMId, Constants.kPanelHandlerSolenoid); // TODO: Change this
You need to add a new ID for the Arm solenoid/the Slide solenoid.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
>                              mSolenoid.set(Constants.kPanelSolenoidExtend);
You should have `kPanelArmSolenoidExtend`, `kPanelSlideSolenoidExtend`.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                        else if (Timer.getFPGATimestamp() > mArmDownTime + Constants.kPanelArmDownTime && newState == mSystemState){
No need for `newState == mSystemState` here because you're not changing `mSystemState`.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                        else if (Timer.getFPGATimestamp() > mEjectTime + Constants.kPanelEjectTime && newState == mSystemState){
No need for `newState == mSystemState` here because you're not changing `mSystemState`.

2019-02-28 04:23 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                        else if (Timer.getFPGATimestamp() > mRetractTime + Constants.kPanelRetractTime && newState == mSystemState){
Here, you must check if `mWantedState == WantedState.EJECT_ROCKET`.

2019-03-02 00:49 UTC, pietroglyph requested changes
Looks pretty good, just a couple of things?

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/Constants.java
> +    public static final int kPanelHandlerArmSolenoid = 25;
Maybe call it `...SolenoidID`?

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/Constants.java
>      public static final boolean kPanelSolenoidRetract = false;
Maybe change to `kPanelSolenoidArmDown` and `...Up` to be more consistent?

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                            mArmSolenoid.set(Constants.kPanelSolenoidRetract);
Probably change this to `Up` as per our conversation.

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                            mSlideSolenoid.set(Constants.kPanelSolenoidExtend);
You should add a constant (see above) for slide solenoid.

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                        else if (Timer.getFPGATimestamp() > mRetractTime + Constants.kPanelRetractTime && newState == mSystemState && mWantedState == WantedState.EJECT_ROCKET){
You don't need `newState == mSystemState` here, because you're not changing the system state.

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                return mSystemState == SystemState.EJECTING_ROCKET;
Return `false` here.

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +        private double mRetractTime;
Change to `Timer`.

2019-03-02 00:49 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                return mSystemState == SystemState.ARM_DOWNING;
Add a `mStateChangedTimer.hasPeriodPassed(Constants.kPanelArmMovementTime)` and associated `private final Timer mStateChangedTimer = new Timer()`.

2019-03-02 02:25 UTC, ronan33 commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                            mArmSolenoid.set(Constants.kPanelArmSolenoidUp);
should be Constants.kPanelArmSolenoidDown

2019-03-02 02:25 UTC, ronan33 commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +                        }
break;

2019-03-02 02:25 UTC, ronan33 commented on src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java
> +            mArmSolenoid.set(Constants.kPanelArmSolenoidUp);
should be down

2019-03-02 02:25 UTC, ronan33 commented on src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java
> +                            mPanelHandler.setWantedState(PanelHandler.WantedState.ARM_DOWN);
!! someone has to add more superstructure states to differentiate between ejecting cargo to the rocket and to the cargo ship. currently this is only set up to eject to the cargo ship

2019-04-03 21:59 UTC, omentic approved these changes
Merging to work on

2019-04-03 21:59 UTC, merged